<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Infrastructure.Messaging</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.5.11" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.11" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Math.Application\Math.Application.csproj" />
    <ProjectReference Include="..\Math.Domain\Math.Domain.csproj" />
    <ProjectReference Include="..\Math.Infrastructure\Math.Infrastructure.csproj" />
  </ItemGroup>

</Project>
